const mongoose = require('mongoose');

const UserSchema = new mongoose.Schema({
    // A unique ID generated by the client to identify the device/user session
    clientId: {
        type: String,
        required: true,
        unique: true,
        index: true,
    },
    tanescoNumber: {
        type: String,
        default: null,
    },
    lastVendDate: {
        type: String, // Storing as 'YYYY-MM-DD' string
        default: null,
    },
}, { timestamps: true });

module.exports = mongoose.model('User', UserSchema);
